package cc.catface.app_base;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by catfaceWYH --> tel|wechat|qq 130 128 92925
 */
public class TestDataSource {


    public static List<String> get_lol_en_names() {
        List<String> datas = new ArrayList<>();
        datas.add("Ahri");
        datas.add("Akali");
        datas.add("Alistar");
        datas.add("Amumu");
        datas.add("Anivia");
        datas.add("Annie");
        datas.add("Ashe");
        datas.add("Blitzcrank");
        datas.add("Brand");
        datas.add("Caitlyn");
        datas.add("Cassiopeia");
        datas.add("ChoGath");
        datas.add("Corki");
        datas.add("Darius");
        datas.add("Diana");
        datas.add("DrMundo");
        datas.add("Delevin");
        datas.add("Elise");
        datas.add("Evelynn");
        datas.add("Ezreal");
        datas.add("Fiddlesticks");
        datas.add("Fiora");
        datas.add("Fizz");
        datas.add("Galio");
        datas.add("Gangplank");
        datas.add("Garen");
        datas.add("Gragas");
        datas.add("Graves");
        datas.add("Hecarim");
        datas.add("Heimerdinger");
        datas.add("Irelia");
        datas.add("Janna");
        datas.add("JarvanⅣ");
        datas.add("Jax");
        datas.add("Jayce");
        datas.add("Karma");
        datas.add("Karthus");
        datas.add("Kassadin");
        datas.add("Katarina");
        datas.add("Kayle");
        datas.add("Kennen");
        datas.add("Khazix");
        datas.add("Kog Maw");
        datas.add("LeBlanc");
        datas.add("Lee sin");
        datas.add("Leona");
        datas.add("lulu");
        datas.add("Lux");
        datas.add("Malphite");
        datas.add("Malzahar");
        datas.add("Maokai");
        datas.add("Yi");
        datas.add("MissFortune");
        datas.add("Monkey king");
        datas.add("Mordekaiser");
        datas.add("Morgana");
        datas.add("Nami");
        datas.add("Nasus");
        datas.add("Nautilus");
        datas.add("Nidalee");
        datas.add("Nocturne");
        datas.add("Nunu");
        datas.add("Olaf");
        datas.add("Orianna");
        datas.add("Pantheon");
        datas.add("Poopy");
        datas.add("Rammus");
        datas.add("Renekton");
        datas.add("Rengar");
        datas.add("Rivan");
        datas.add("Rumble");
        datas.add("Ryze");
        datas.add("Sejuani");
        datas.add("Shaco");
        datas.add("Shen");
        datas.add("Shyvana");
        datas.add("Singed");
        datas.add("Sion");
        datas.add("Sivir");
        datas.add("Skarner");
        datas.add("Sona");
        datas.add("Soraka");
        datas.add("Swain");
        datas.add("Syndra");
        datas.add("Talon");
        datas.add("Taric");
        datas.add("Teemo");
        datas.add("Thresh");
        datas.add("Tristana");
        datas.add("Trundle");
        datas.add("Tryndamere");
        datas.add("Twisted Fate");
        datas.add("Twitch");
        datas.add("Udyr");
        datas.add("Urgot");
        datas.add("Varus");
        datas.add("Vayne");
        datas.add("Veigar");
        datas.add("Vi");
        datas.add("Viktor");
        datas.add("Vladimir");
        datas.add("Volibear");
        datas.add("Warwick");
        datas.add("Xerath");
        datas.add("XinZhao");
        datas.add("Yorick");
        datas.add("Zed");
        datas.add("Ziggs");
        datas.add("Zilean");
        datas.add("Zyra");
        Collections.shuffle(datas);
        return datas;
    }

    public static List<String> get_lol_zh_names() {
        List<String> datas = new ArrayList<>();
        datas.add("阿狸");
        datas.add("阿卡丽");
        datas.add("阿利斯塔");
        datas.add("阿木木");
        datas.add("艾尼维亚");
        datas.add("安妮");
        datas.add("艾希");
        datas.add("布里茨");
        datas.add("布兰德");
        datas.add("凯特琳");
        datas.add("卡西奥佩娅");
        datas.add("科’加斯");
        datas.add("库奇");
        datas.add("德莱厄斯");
        datas.add("黛安娜");
        datas.add("蒙多医生");
        datas.add("德莱文");
        datas.add("伊莉斯");
        datas.add("伊芙琳");
        datas.add("伊泽瑞尔");
        datas.add("费德提克");
        datas.add("剑姬");
        datas.add("菲兹");
        datas.add("加里奥");
        datas.add("普朗克");
        datas.add("盖伦");
        datas.add("古拉加斯");
        datas.add("格雷福斯");
        datas.add("赫卡里姆");
        datas.add("黑默丁格");
        datas.add("伊瑞利亚");
        datas.add("迦娜");
        datas.add("嘉文四世");
        datas.add("贾克斯");
        datas.add("杰斯");
        datas.add("卡尔玛");
        datas.add("卡尔萨斯");
        datas.add("卡萨丁");
        datas.add("卡特琳娜");
        datas.add("凯尔");
        datas.add("凯南");
        datas.add("卡’兹克");
        datas.add("克格’莫");
        datas.add("乐芙兰");
        datas.add("李青");
        datas.add("蕾欧娜");
        datas.add("璐璐");
        datas.add("拉克丝");
        datas.add("墨菲特");
        datas.add("玛尔扎哈");
        datas.add("茂凯");
        datas.add("易");
        datas.add("厄运小姐");
        datas.add("孙悟空");
        datas.add("莫德凯撒");
        datas.add("莫甘娜");
        datas.add("娜美");
        datas.add("内瑟斯");
        datas.add("诺提勒斯");
        datas.add("奈德丽");
        datas.add("魔腾");
        datas.add("努努");
        datas.add("奥拉夫");
        datas.add("奥莉安娜");
        datas.add("潘森");
        datas.add("波比");
        datas.add("拉莫斯");
        datas.add("雷克顿");
        datas.add("雷恩加尔");
        datas.add("瑞文");
        datas.add("兰博");
        datas.add("瑞兹");
        datas.add("瑟庄妮");
        datas.add("萨科");
        datas.add("慎");
        datas.add("希瓦娜");
        datas.add("辛吉德");
        datas.add("赛恩");
        datas.add("希维尔");
        datas.add("斯卡纳");
        datas.add("娑娜");
        datas.add("索拉卡");
        datas.add("斯维因");
        datas.add("辛德拉");
        datas.add("泰隆");
        datas.add("塔里克");
        datas.add("提莫");
        datas.add("锤石");
        datas.add("崔丝塔娜");
        datas.add("特兰德尔");
        datas.add("泰达米尔");
        datas.add("崔斯特");
        datas.add("图奇");
        datas.add("乌迪尔");
        datas.add("厄加特");
        datas.add("韦鲁斯");
        datas.add("薇恩");
        datas.add("维伽");
        datas.add("蔚");
        datas.add("维克托");
        datas.add("弗拉基米尔");
        datas.add("沃利贝尔");
        datas.add("沃里克");
        datas.add("泽拉斯");
        datas.add("赵信");
        datas.add("约里克");
        datas.add("劫");
        datas.add("吉格斯");
        datas.add("基兰");
        datas.add("婕拉");
        Collections.shuffle(datas);
        return datas;
    }


    /* 类似搜索记录中的流式布局需要显示的测试数据源 */
    public static List<String> getFlowLayoutDatas() {
        List<String> datas = new ArrayList<>();
        datas.add("苏打粉");
        datas.add("我去");
        datas.add("我去偷他企鹅");
        datas.add("请问发大水");
        datas.add("鼎折覆餗归属地");
        datas.add("阿盘萨");
        datas.add("和核桃仁");
        datas.add("搞好");
        datas.add("如儿童愈加广泛");
        datas.add("减肥刚到呢");
        datas.add("电负荷然后他");
        datas.add("儿童");
        datas.add("哦");
        datas.add("调结构和");
        datas.add("而他也认同也太容易");
        datas.add("他认可与");
        datas.add("老有利于录音");
        datas.add("卡特阔腿裤");
        datas.add("绿林豪客体育课太远了体育课");
        Collections.shuffle(datas);
        return datas;
    }


    /* 类似通讯录列表的粘性头布局控件的测试数据源 */
    public static List<String> getStickyListDatas() {
        List<String> datas = new ArrayList<>();
        datas.add("dathbf");
        datas.add("muhstn");
        datas.add("pojbEOF");
        datas.add("lahbnabf");
        datas.add("uyjrdnsg");
        datas.add("irkyjmdnhsg");
        datas.add("asdf");
        datas.add("asgcz");
        datas.add("zxc");
        datas.add("lthey");
        datas.add("zxvasd");
        datas.add("dhgj");
        datas.add("ghjk");
        datas.add("kuy");
        datas.add("fgkk");
        datas.add("ukyk");
        datas.add("fgyiyu");
        datas.add("list4");
        datas.add("yuey");
        datas.add("trujyd");
        datas.add("jt");
        datas.add("dmyxktf");
        datas.add("rtjxg");
        datas.add("tshy");
        datas.add("zhfd");
        datas.add("cbvg");
        datas.add("dhx");
        datas.add("dxfgc");
        datas.add("xgncfxf");
        datas.add("xgnh");
        datas.add("xgnh");
        datas.add("tr");
        datas.add("dhte");
        datas.add("dhfx");
        datas.add("zdhf");
        datas.add("zhdea");
        datas.add("znd");
        datas.add("tnj");
        datas.add("tgnjf");
        datas.add("tjgrs");
        datas.add("sewtg");
        datas.add("kuyf");
        datas.add("uil");
        datas.add("kyfu");
        datas.add("ughmk");
        datas.add("fyukm");
        datas.add("232fyukm");
        datas.add("246ergsd");
        datas.add("56erth");
        datas.add("45erhtgndf");
        datas.add("345hdherth");
        datas.add("4365rhtrehbgf");
        datas.add("测试中文");
        datas.add("测试上岛咖啡你那");
        datas.add("让他华商报");
        datas.add("阴合势方巩");
        datas.add("有人你还能购房人");
        datas.add("又如何GV赛诺菲什么样");
        datas.add("#sdfbbs");
        datas.add("#sdbnert");
        datas.add("%dngf");
        datas.add(" snf失败");
        Collections.shuffle(datas);
        return datas;
    }


    public static final String[] chars = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"};

    public static final String[] nums = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};

    public static final String[] symbles = {"~", "!", "@", "#", "$", "%", "^", "&", "*"};

    public static final String[] words = {"富强", "民主", "文明", "和谐", "自由", "平等", "公正", "法治", "爱国", "敬业", "诚信", "友善"};
}
