package cc.catface.app_base.greendao.domain.greendao_gen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.catface.app_base.greendao.Memo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEMO".
*/
public class MemoDao extends AbstractDao<Memo, Long> {

    public static final String TABLENAME = "MEMO";

    /**
     * Properties of entity Memo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property Date = new Property(2, long.class, "date", false, "DATE");
        public final static Property Tag = new Property(3, String.class, "tag", false, "TAG");
        public final static Property Stars = new Property(4, int.class, "stars", false, "STARS");
    }


    public MemoDao(DaoConfig config) {
        super(config);
    }
    
    public MemoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEMO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"CONTENT\" TEXT," + // 1: content
                "\"DATE\" INTEGER NOT NULL ," + // 2: date
                "\"TAG\" TEXT," + // 3: tag
                "\"STARS\" INTEGER NOT NULL );"); // 4: stars
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEMO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Memo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
        stmt.bindLong(3, entity.getDate());
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
        stmt.bindLong(5, entity.getStars());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Memo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
        stmt.bindLong(3, entity.getDate());
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(4, tag);
        }
        stmt.bindLong(5, entity.getStars());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Memo readEntity(Cursor cursor, int offset) {
        Memo entity = new Memo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.getLong(offset + 2), // date
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tag
            cursor.getInt(offset + 4) // stars
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Memo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.getLong(offset + 2));
        entity.setTag(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStars(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Memo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Memo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Memo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
